version: '3.8'

services:
  mcp-demo:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    command: ["node", "index.js", "backend"]
    
  mcp-demo-test:
    build: .
    depends_on:
      - mcp-demo
    environment:
      - NODE_ENV=test
    command: ["node", "test.js"]
    profiles:
      - test

networks:
  default:
    name: mcp-demo-network
